language: rust
env:
  global:
    - PROJECT_NAME: gprompt
    - RUST_BACKTRACE: full
    - TMPDIR=/tmp
addons:
  apt:
    packages:
      - git
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
